server:
  port: 80
  servlet:
    context-path: /wjd

spring:
  thymeleaf:
    #前缀，也就是模板存放的路径
    prefix: classpath:/templates/
    #编码格式
    encoding: UTF-8
    #关闭缓存，不然无法看到实时页面
    cache: false
    #后缀
    suffix: .html
    #设置不严格的html
    mode: HTML
    servlet:
      content-type: text/html
    check-template-location: false